language: node_js
node_js:
 - “iojs”
 - “10"
cache: 
  - node_modules
env:
 - CXX=g++-5
addons:
 apt:
   sources:
     - ubuntu-toolchain-r-test
   packages:
     - g++-5
script:
  - "npm run test"
deploy:
  provider: heroku
  api_key:
    secure: "HEROKU_API_KEY"
  app: bizbloom
  on:
    repo: nionata/Bloom
